# ~/manga-automobiles/backend/Cargo.toml
[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[dependencies] # Keep only this one
actix-web = "4"
serde       = { version = "1.0", features = ["derive"] }
serde_json= "1.0"
